import json, re
from pathlib import Path

BASE = Path('/home/node/.openclaw/workspace/met_term')
DATA = BASE / 'data'

source_files = {
    'i': DATA / 'i_terms_source.txt',
    'j': DATA / 'j_terms_source.txt',
}

exact_translation = {
    'I and Q channels': '同相與正交通道',
    'IAC': 'IAC 指數／類別',
    'IAS': '指示空速',
    'Ibe wind': '伊貝風',
    'IBL': '內邊界層',
    'ICAO': '國際民用航空組織',
    'IF': '中頻',
    'IF signal': '中頻訊號',
    'IF–THEN rule': 'IF–THEN 規則',
    'IFF': '敵我識別系統',
    'IFR': '儀器飛航規則',
    'IGRF': '國際地磁參考場',
    'ILS': '儀器降落系統',
    'Improved TIROS Operational System': '改良型 TIROS 作業系統',
    'IN counter': '冰核計數器',
    'Indian National Satellite System': '印度國家衛星系統',
    'Indonesian Throughflow': '印尼穿流',
    'Inflow': '流入',
    'Infrared Interferometer Spectrometer': '紅外干涉光譜儀',
    'INS': '慣性導航系統',
    'INSAT': '印度國家衛星',
    'Internal boundary layer': '內部邊界層',
    'International Geomagnetic Reference Field': '國際地磁參考場',
    'International Pyrheliometric Scale': '國際直接日射量表',
    'International Satellite Cloud Climatology Project': '國際衛星雲氣候計畫',
    'International System of Units': '國際單位制',
    'International Table calorie': '國際表卡路里',
    'International Units': '國際單位',
    'Interplanetary magnetic field': '行星際磁場',
    'Inverted trough': '倒槽',
    'Ion cloud': '離子雲',
    'Ionizing radiation': '游離輻射',
    'IPS': '圖像處理系統',
    'IR': '紅外線',
    'IRIS': '虹彩現象／IRIS 系統',
    'ISCCP': '國際衛星雲氣候計畫',
    'ITcal': '國際表卡路里',
    'ITCZ': '熱帶輻合帶',
    'ITOS': '改良型 TIROS 作業系統',
    'J process': 'J 過程',
    "j''-value": "j'' 值",
    'Jacobian': '雅可比量',
    'January thaw': '一月融凍期',
    'Japan Sea Deep Water': '日本海深層水',
    'Japan Sea Middle Water': '日本海中層水',
    'jauk': '焦克風',
    'jet': '噴流',
    'jet axis': '噴流軸',
    'jet streak': '急流核',
    'jet stream': '急流',
    'jet stream axis': '急流軸',
    'jet stream cirrus': '急流卷雲',
    'jet stream core': '急流核心',
    'jet-effect wind': '噴流效應風',
    'jetlet': '小尺度噴流',
    'Jevons effect': '杰文斯效應',
    'jimsphere': '金斯球探空儀',
    'jochwinde': '山口強風',
    'Johnson–Williams liquid water probe': 'Johnson–Williams 液態含水量探針',
    'JONSWAP': 'JONSWAP 譜型',
    'JONSWAP spectrum': 'JONSWAP 波譜',
    'Jordan sunshine recorder': 'Jordan 日照記錄器',
    'joule': '焦耳',
    "Joule's constant": '焦耳常數',
    'jump': '躍變',
    'jump model': '躍變模式',
    'junction streamer': '交會流線',
    'Junge aerosol layer': '榮格氣膠層',
    'junk wind': '舢舨風',
    'junta': '焚風型局地風',
    'juran': '朱蘭風',
    'jury problem': '陪審團問題',
}

exact_definition = {
    'I and Q channels': '在遙測、雷達或通訊接收中，將複數訊號分解為同相（I）與正交（Q）兩個分量的通道，用以重建振幅、相位與多普勒資訊。',
    'IAS': '航空上依空速表直接讀得、尚未完全校正位置與儀器誤差的空速，是飛航操作常用之基本速度量。',
    'IBL': '指下墊面性質突變後，近地層因動量、熱量與水氣重新調整而形成的內部邊界層。',
    'ICAO': '制定國際民航標準與作業程序的專門機構，其規範廣泛用於航空氣象觀測、報告、預報與飛航安全。',
    'ice': '水在 0°C 以下或適當壓力條件下形成的固態相，在雲微物理、冰凍圈與航空結冰研究中為重要介質。',
    'ice accretion': '過冷水滴、雪粒或冰晶附著於物體表面並持續增長的結冰過程，常見於機體、電線與地面結構。',
    'ice age': '地球氣候長期偏冷、冰蓋與冰川大幅擴張的地質時期。',
    'ice and snow albedo–temperature feedback': '冰雪高反照率使地表吸收太陽能減少而降溫，降溫又促進冰雪維持或擴張的正回饋機制。',
    'ice band': '由海冰、冰山或浮冰沿一定方向聚集形成的帶狀區域。',
    'ice bands': '由海冰、冰山或浮冰沿一定方向聚集形成的多條帶狀區域。',
    'ice blink': '低雲底部受大片冰雪反射而呈現的白色亮光，可作為遠方海冰或積雪存在的視覺指標。',
    'ice breakup': '河冰、湖冰或海冰因升溫、流動或機械作用而破裂解體的過程。',
    'ice cap': '覆蓋範圍較冰原小、通常覆蓋高地或島嶼的穹形冰體。',
    'ice crystal': '大氣中由水汽凝華形成的固態冰粒，是高雲、降雪與結冰現象的重要微物理成分。',
    'ice day': '一日內最高氣溫持續低於 0°C 的日子。',
    'ice drift': '海冰在風力、海流與科氏力共同作用下的漂移運動。',
    'ice edge': '海冰區與開放水面之間的邊界。',
    'ice fog': '由大量懸浮冰晶組成、常出現在極寒環境中的霧。',
    'ice forecast': '針對海冰分布、濃度、厚度、漂移與冰緣變化所作的預報。',
    'ice formation on aircraft': '飛機表面因過冷水滴撞擊凍結或冰晶沉積所造成的結冰現象，會影響升力、阻力與飛航安全。',
    'ice front': '海冰或冰蓋前緣與鄰近海域、陸地或其他冰體之交界。',
    'ice jam': '河道中浮冰或碎冰壅塞聚積，造成水位抬升與回水效應的現象。',
    'ice keel': '海冰下方延伸至水中的脊狀部分，常為壓積冰構造的一部分。',
    'ice mixing ratio': '單位質量乾空氣中所含冰相水成分的質量。',
    'ice multiplication': '雲中冰晶數目藉由次生冰生成機制而增加的現象。',
    'ice needle': '呈細長針狀的冰晶，常在低溫高濕環境中形成。',
    'ice nuclei counter': '用以量測空氣中冰核濃度或活化數目的儀器。',
    'ice nucleus': '可促使過冷水滴凍結或促進水汽直接凝華成冰的微粒。',
    'Ice pellets': '雨滴或融雪再凍結後形成的小型透明或半透明冰粒，屬凍結性降水之一。',
    'ice plain': '冰體表面相對平坦、起伏較小的區域。',
    'ice point': '純水與純冰在標準壓力下達相平衡時的溫度，常取為 0°C。',
    'ice shelf': '由陸上冰川或冰蓋向海面延伸並漂浮於海上的厚大冰板。',
    'ice storm': '以凍雨或大量結冰為主要特徵、會在地物表面形成顯著覆冰的風暴。',
    'ice stream': '冰蓋或冰原中流速顯著較快、受基底與應力條件控制的狹長流動帶。',
    'ice tongue': '由冰川前緣向海或湖面伸出的狹長舌狀冰體。',
    'iceberg': '自冰川或冰棚崩解後漂浮於海上的大型淡水冰塊。',
    'iced firn': '經融化再凍結而含有顯著冰層或冰透鏡的粒雪。',
    'icefall': '冰川在陡坡上因流動加速與張裂而形成的破碎冰瀑地形。',
    'Icelandic low': '位於北大西洋冰島附近的半永久性低壓中心，對北大西洋風暴路徑與歐洲天氣有重要影響。',
    'icing': '過冷水滴或冰晶在物體表面形成積冰的現象。',
    'icing intensity': '表示結冰累積快慢與嚴重程度的強度分級。',
    'icing level': '大氣中容易發生結冰或積冰的重要高度層。',
    'icing-rate meter': '量測單位時間內積冰厚度或質量增長率的儀器。',
    'ideal fluid': '理論上不具黏滯性且常假設不可壓縮的流體，用於流體力學推導。',
    'ideal gas': '滿足理想氣體方程式、假設分子體積與分子間作用可忽略的氣體模型。',
    'identical twin integrations': '以幾乎相同模式配置進行成對數值積分，用來檢驗敏感度、可預報度或資料同化效果的實驗設計。',
    'IF': '在無線電、雷達與遙測系統中，將接收訊號經混頻轉換後所得之中間頻率。',
    'IF signal': '經混頻後落於中頻範圍、便於放大與濾波處理的訊號。',
    'IF–THEN rule': '以條件與結果表示的規則形式，常用於專家系統、推論引擎與自動判識流程。',
    'IFF': '供航空與雷達系統辨識友軍、敵軍或未知目標身分的電子識別系統。',
    'IFR': '飛航在能見度或雲高不足時，依儀器與航管程序而非目視條件進行之飛航規則。',
    'IGRF': '描述地球主磁場全球平均分布及其長期變化的國際參考模型。',
    'illuminance': '單位面積上接受之可見光通量，通常以勒克斯表示。',
    'illumination': '光源對目標或觀測面的照明狀態與光照分布。',
    'ILS': '協助航空器依地面無線電導引進場與降落的精密導航系統。',
    'image': '由觀測、攝影、雷達或衛星感測所形成之空間分布圖像，用以呈現目標輻射、反射或回波特徵。',
    'image enhancement': '透過對比增強、濾波、色階轉換等方式提升圖像可辨識度的處理。',
    'image processing': '對數位影像進行校正、濾波、分類、特徵萃取與顯示轉換的技術流程。',
    'imbibition': '多孔介質因毛細作用而吸入液體的過程。',
    'immiscible displacement': '在多孔介質中，一種與原流體不互溶的流體將其推替的過程。',
    'impactor': '利用顆粒慣性撞擊原理分離或收集氣膠粒子的取樣裝置。',
    'impinger': '藉由氣流通過液體並使粒子或氣體被捕集的取樣器。',
    'implicit time difference': '數值方法中使用未來時間層未知量建立差分式的時間離散法，通常較具穩定性。',
    'Improved TIROS Operational System': '早期氣象衛星作業系統之一，承接 TIROS 計畫並提升全球雲圖與環境觀測能力。',
    'IN counter': '用於統計空氣中活化冰核數目之儀器。',
    'indicated airspeed': '由空速表直接讀得並經有限校正後表示的飛機相對氣流速度。',
    'indicated altitude': '由高度表在既定設定值下直接顯示的高度。',
    'indirect cell': '熱力驅動方向與實際質量環流方向相反的環流胞，如中緯度費瑞耳環流。',
    'indirect circulation': '藉由外部強迫或動力調整維持、其質量輸送方向與局地熱力驅動相反的環流。',
    'Indonesian Throughflow': '太平洋海水經印尼群島海峽流入印度洋的跨海盆海流系統，對熱量與鹽度輸送極為重要。',
    'induction charging mechanism': '粒子在外加電場或鄰近帶電體影響下產生電荷分離並帶電的機制。',
    'induction icing': '因進氣或導流結構使過冷水滴易於撞擊並凍結而形成的結冰。',
    'industrial climatology': '研究氣候條件對工業設施、流程、能源需求與作業管理影響的應用氣候學分支。',
    'industrial meteorology': '將氣象資料與預報應用於工業安全、生產調度、污染擴散及能源管理的專業領域。',
    'inertia wave': '受慣性力主導、振動頻率接近科氏參數的波動。',
    'inertial circle': '在無壓力梯度與無摩擦近似下，流體質點因科氏力而作之圓形運動軌跡。',
    'inertial current': '主要受地轉偏向力與慣性作用控制的海流或流速振盪。',
    'inertial flow': '以慣性效應為主導、外力影響相對較小的流動。',
    'inertial force': '在非慣性參考系中為維持牛頓運動定律形式而引入的表觀力。',
    'inertial instability': '流體受擾動後若角動量分布不穩定而使擾動增長的動力不穩定。',
    'inertial oscillation': '在近乎無摩擦且無顯著壓力梯度下，由科氏力控制的週期性速度振盪。',
    'inertial period': '慣性振盪完成一個週期所需的時間，與所在地緯度及科氏參數有關。',
    'inertial range': '湍流能譜中能量主要由大尺度傳向小尺度、但尚未被黏滯耗散主導的尺度範圍。',
    'inertial stability': '描述流體對軸對稱擾動所具抗拒離心失穩能力的性質。',
    'inferior mirage': '近地層強烈增溫致折射率垂直梯度異常時，遠物影像出現在真實物體下方的海市蜃樓。',
    'infiltration': '地表水經土壤孔隙向下進入土層的過程。',
    'infiltration capacity': '在既有土壤條件下，土壤可吸納入滲水量的最大速率。',
    'infiltrometer': '量測土壤入滲能力或入滲速率的儀器。',
    'infrared': '波長長於可見紅光、短於微波之電磁輻射區段。',
    'infrared image': '以紅外輻射亮溫或輻射強度生成的影像，常用於觀測雲頂溫度與地表熱特徵。',
    'infrared radiation': '波長位於紅外區之電磁輻射，是地球長波放射與遙測觀測的重要波段。',
    'infrared radiometry': '量測目標紅外輻射強度、亮溫或光譜特性的技術。',
    'infrared spectrometer': '量測紅外光譜分布以分析物質組成、溫度或輻射特性的儀器。',
    'infrasound': '頻率低於人耳可聽範圍下限的聲波，常用於監測火山、爆炸、雷暴或大氣波動。',
    'initial condition': '數值模式或微分方程在起算時刻所指定的狀態場。',
    'initial-value problem': '已知起始時刻或起始位置條件，求解方程隨時間或空間演變的問題。',
    'initialization': '為使數值模式初始場與控制方程及觀測條件更相容而進行的調整程序。',
    'inland sea breeze': '由內陸大型湖泊或海面與鄰近陸地受熱差異所驅動、白天由水域吹向陸地的局地風。',
    'inner layer': '邊界層中最接近下墊面的區域，其流場主要受地表粗糙度與局地通量控制。',
    'INS': '利用加速度計與陀螺儀推算位置、速度與姿態的自主導航系統。',
    'INSAT': '印度用於氣象、通訊及相關應用之國家衛星系列。',
    'insolation': '太陽輻射入射至地表或大氣頂的能量通量。',
    'instability': '系統受微小擾動後會使擾動增大而偏離原平衡狀態的性質。',
    'instability line': '大氣中不穩定度顯著集中、常伴隨對流發展的線狀區域。',
    'instantaneous field of view': '遙測儀器在某一瞬間所對應的地面或目標視場範圍。',
    'instantaneous unit hydrograph': '假設有效降雨脈衝於瞬時輸入時，流域出口產生之單位歷線。',
    'instrument flight rules': '規範航空器在依賴機載與地面儀器資訊下飛航的程序與最低條件。',
    'instrument landing system': '透過航向台與下滑道提供精密橫向及垂直導引的降落系統。',
    'instrument shelter': '保護氣象儀器免受直射日光與降水干擾、同時維持良好通風的百葉箱或類似設施。',
    'integral depth scale': '描述湍流或流體結構在垂直方向上具有主要相關性的代表深度尺度。',
    'integral length scales': '由相關函數積分定義之代表性大尺度渦旋尺寸。',
    'intensity–duration–frequency curve': '描述降雨強度、持續時間與重現期之間關係的工程水文曲線。',
    'interception': '降水被植被冠層、建築物或其他地表覆蓋截留而未立即到達地面的過程。',
    'interchange coefficient': '表徵動量、熱量或物質在湍流中交換效率的係數。',
    'interface': '兩種介質、氣團、水團或物理性質明顯不同區域之間的交界面。',
    'interference': '兩個或多個波動、訊號或輻射場疊加後產生增強或抵銷的現象。',
    'interferometer': '利用波相位差或光程差進行精密量測的儀器。',
    'interferometry': '藉由分析干涉條紋或相位差來推求幾何、位移或輻射資訊的技術。',
    'interflow': '土壤中在地表以下、沿較淺土層側向流動的地下水流。',
    'interglacial': '兩次冰期之間較為溫暖、冰量相對減少的時期。',
    'intermediate frequency': '介於射頻與基帶之間、經混頻後用於後續放大處理的頻率。',
    'intermediate water': '位於海洋中層、介於表層水與深層水之間且具有特定溫鹽特性的水團。',
    'internal energy': '系統內部分子平動、轉動、振動與相互作用所包含的總能量。',
    'internal gravity wave': '因浮力恢復力作用而在穩定成層流體內傳播的重力波。',
    'internal tides': '由潮汐流越過地形後在海洋密度分層內激發的內波型潮汐。',
    'internal wave': '存在於流體內部密度界面或穩定分層中的波動。',
    'international analysis code': '國際間用於交換分析資料或天氣圖資訊的標準編碼系統。',
    'international standard atmosphere': '供航空、工程與儀器校準使用的標準大氣垂直結構。',
    'international synoptic code': '國際天氣觀測與綜觀報告所使用的標準代碼。',
    'interplanetary dust': '分布於行星際空間、由彗星、隕石或其他天體來源產生的微粒。',
    'interpolation': '依已知資料點推估其間未知值的方法。',
    'intertropical convergence zone': '赤道附近東北與東南信風匯聚、對流旺盛且降雨頻繁的帶狀區域。',
    'intertropical front': '熱帶區域兩支不同來源氣流交會形成的鋒狀過渡帶。',
    'intracloud flash': '發生於同一雲體內不同電荷區之間的閃電放電。',
    'intrinsic permeability': '多孔介質本身在不考慮流體性質時對流動能力的固有表徵。',
    'inverse-square law': '某些場量或輻射強度隨距離平方反比衰減的定律。',
    'inversion': '氣溫隨高度上升反而增加的穩定層結。',
    'inverted barometer effect': '海面或水面高度對大氣壓變化的近似反向響應，高壓時水位偏低、低壓時水位偏高。',
    'Inverted trough': '在天氣圖上向高壓一側延伸、形狀與一般槽線相反的低壓槽。',
    'inviscid fluid': '假設黏滯性可忽略的理想化流體。',
    'ion': '原子或分子因失去或獲得電子而帶有淨電荷的粒子。',
    'ion chromatography': '利用離子交換與檢測技術分離並定量離子成分的分析方法。',
    'ionization': '中性原子或分子因能量作用而形成離子的過程。',
    'ionization chamber': '量測游離輻射或帶電粒子通量時，利用氣體游離電流原理的偵測器。',
    'ionogram': '以離子探測儀量測並繪示電離層反射回波延遲與頻率關係的圖。',
    'ionosphere': '位於高層大氣中、受太陽紫外與粒子輻射作用而含有大量離子與自由電子的區域。',
    'ionosonde': '用以探測電離層高度與電子密度結構的垂直探空雷達。',
    'ionospheric storm': '受太陽活動與地磁擾動影響，電離層電子密度與結構出現顯著異常變化的現象。',
    'iridescent clouds': '雲滴或細小冰晶對陽光繞射所產生的彩虹般雲色現象。',
    'irradiance': '單位面積所接收的輻射通量密度。',
    'irradiation': '物體表面或介質接受輻射照射的作用過程。',
    'irrigation': '將水人工引入土壤或作物根區以補充天然降水不足的農業供水措施。',
    'irrotational': '流場局部渦度為零或可視為無旋的性質。',
    'isallobar': '表示同一氣壓變化量的等值線。',
    'isallobaric wind': '由水平氣壓變化梯度驅動、與氣壓傾向分布有關的年齡不平衡風分量。',
    'isallotherm': '表示同一氣溫變化量的等值線。',
    'ISCCP': '以衛星資料建立全球雲量、雲頂與輻射氣候資料集的國際合作計畫。',
    'isentrope': '位溫相同各點連成的線。',
    'isentropic analysis': '在等熵或等位溫面上分析大氣運動與熱力結構的方法。',
    'isentropic surface': '位溫處處相同的曲面。',
    'isobar': '表示同一氣壓值的等值線。',
    'isobaric analysis': '在等壓面上分析高度、溫度、風場與其他氣象要素的綜觀方法。',
    'isobaric surface': '氣壓相同各點所構成的曲面。',
    'isobath': '表示同一水深的等值線。',
    'isobront': '表示雷暴同時發生時間的等值線。',
    'isoceraunic line': '連接年平均雷日數相同地點的等值線。',
    'isochasm': '表示極光出現頻率相同的等值線。',
    'isochrone': '表示事件同時到達或發生時間相同的等時線。',
    'isodrosotherm': '表示相同露點溫度的等值線。',
    'isoecho': '表示雷達回波強度相同的等值線。',
    'isogeotherm': '表示相同地溫的等值線。',
    'isogon': '表示相同磁偏角的等值線。',
    'isohaline': '表示相同鹽度的等值線。',
    'isohel': '表示日照量或日照時數相同的等值線。',
    'isohume': '表示相同濕度值的等值線。',
    'isohyet': '表示相同降水量的等值線。',
    'isokinetic sampling': '使採樣口流速與外界來流速度相同，以降低粒子取樣偏差的方法。',
    'isoline': '表示某一物理量相同的通用等值線。',
    'isoneph': '表示雲量相同的等值線。',
    'isopluvial': '表示相同降雨條件或降雨量的等值線或分布。',
    'isopycnal': '表示相同密度的等值線或等密度面。',
    'isopycnal mixing': '沿等密度面進行的物質或熱鹽交換。',
    'isotach': '表示相同風速的等值線。',
    'isotherm': '表示相同溫度的等值線。',
    'isothermal atmosphere': '垂直方向上溫度近似不隨高度變化的大氣。',
    'isotopic tracer': '利用同位素作為示蹤物以追蹤物質來源、混合與傳輸的技術。',
    'isotropic turbulence': '各方向統計性質近似相同的湍流。',
    'ITCZ': '位於熱帶低緯、由兩半球信風輻合而成的主要對流與降雨帶。',
    'ivory point': '早期濕度觀測中以象牙材料製成、利用吸濕變形特性作為指示元件的測濕點或構件。',
    'J process': '雲微物理或放射轉換中使用的參數化過程名稱，實際意義需依模式或文獻中的 J 項定義判讀。',
    "j''-value": '用於特定理論推導、座標轉換或參數化公式中的二階導出參數，其確切物理意義需依原方程定義而定。',
    'Jacobian': '描述座標轉換局部伸縮與方向改變關係的行列式或矩陣，在數值模式與流體力學中常用於變數轉換。',
    'January thaw': '冬季中期短暫回暖並伴隨積雪融化的天氣事件。',
    'Japan Sea Deep Water': '形成於日本海深層、具低溫高溶氧等特徵的深水水團。',
    'Japan Sea Middle Water': '位於日本海中層、具有特定溫鹽與通風特徵的中層水團。',
    'jauk': '阿爾卑斯或周邊山區地方性風名，通常指受地形控制的局地強風。',
    'jet': '由高速流體或高風速氣流形成的狹窄帶狀噴射流。',
    'jet axis': '噴流速度最大值沿流向連成的主軸線。',
    'jet streak': '急流中局部風速特別強的區段。',
    'jet stream': '位於對流層上部或平流層下部、呈狹長帶狀分布的強風帶。',
    'jet stream axis': '急流核心沿空間延伸所構成的主軸。',
    'jet stream cirrus': '受急流區上升與風切影響，在高空形成或維持的卷雲。',
    'jet stream core': '急流內風速最大、動量最集中的核心區域。',
    'jet-effect wind': '受噴流加速、導流或地形噴嘴效應增強的局地強風。',
    'jetlet': '尺度較小、壽命較短的局地噴流結構。',
    'Jevons effect': '效率提高反而導致資源總消耗增加的反彈效應概念，亦可延伸用於能源或氣候政策討論。',
    'jimsphere': '以可追蹤輕球搭配定位系統量測高空風場的探空裝置。',
    'jochwinde': '經山口或鞍部加速通過的地形強風。',
    'Johnson–Williams liquid water probe': '安裝於航空器上、利用受熱元件響應量測雲中液態含水量的探針。',
    'JONSWAP': '北海聯合波浪觀測計畫衍生之風浪譜參數化架構，廣用於海洋工程。',
    'JONSWAP spectrum': '用於描述受限發展風浪頻譜形狀的經驗波譜模型。',
    'Jordan sunshine recorder': '以感光或熱效應記錄日照持續時間的儀器。',
    'joule': '國際單位制中的能量與作功單位。',
    "Joule's constant": '用於表示熱與機械能等價關係的常數。',
    'jump': '流體或場量在短距離內出現近似不連續的突變現象，如水躍或壓力躍變。',
    'jump model': '用於描述狀態量突變轉換或分段躍遷行為的數學或數值模型。',
    'junction streamer': '雷暴電場中由不同放電通道交會延伸的細絲狀先導或流注。',
    'Junge aerosol layer': '位於平流層下部、由硫酸鹽等微粒構成的全球性背景氣膠層。',
    'junk wind': '東亞沿海航海語中的地方風名，指適合帆船航行或與季風轉變相關的風。',
    'junta': '地方性風名，通常指在特定地形或季節條件下出現的局地風。',
    'juran': '地方性風名，常指受區域地形與壓力分布控制的局地風。',
    'jury problem': '在統計決策或集合判斷中，分析多個判斷者組合後正確率的理論問題。',
}

phrase_map = {
    'ice-crystal': '冰晶', 'ice crystal': '冰晶', 'ice': '冰',
    'icing': '積冰', 'infrared': '紅外', 'internal': '內部', 'international': '國際',
    'interplanetary': '行星際', 'intertropical': '熱帶輻合', 'intermediate': '中層',
    'inertial': '慣性', 'inertia': '慣性', 'ionospheric': '電離層', 'ionosphere': '電離層',
    'ionization': '游離', 'ion': '離子', 'inversion': '逆溫', 'instability': '不穩定',
    'instrument': '儀器', 'landing': '降落', 'flight': '飛航', 'analysis': '分析', 'chart': '圖',
    'surface': '面', 'layer': '層', 'stream': '流', 'current': '流', 'wave': '波', 'wind': '風',
    'front': '鋒', 'line': '線', 'cloud': '雲', 'fog': '霧', 'storm': '暴風', 'spectrum': '譜',
    'recorder': '記錄器', 'probe': '探針', 'counter': '計數器', 'meter': '計', 'ratio': '混合比',
    'temperature': '溫度', 'radiation': '輻射', 'radiometry': '輻射測量', 'spectrometer': '光譜儀',
    'processing': '處理', 'image': '影像', 'satellite': '衛星', 'system': '系統', 'code': '代碼',
    'water': '水', 'deep': '深層', 'middle': '中層', 'axis': '軸', 'core': '核心', 'thaw': '融凍',
    'jump': '躍變', 'process': '過程', 'problem': '問題', 'constant': '常數', 'energy': '能量',
    'accretion': '積聚', 'age': '期', 'snow': '雪', 'albedo': '反照率', 'feedback': '回饋',
    'apron': '冰裙', 'band': '帶', 'bands': '帶', 'bay': '灣', 'blink': '冰映光', 'breakup': '解凍破裂',
    'cover': '覆蓋', 'crust': '殼', 'day': '日', 'desert': '荒漠', 'drift': '漂移', 'edge': '邊緣',
    'field': '場', 'flow': '流動', 'flowers': '冰花', 'foot': '冰腳', 'forecast': '預報', 'formation': '形成',
    'island': '冰島', 'jam': '冰塞', 'keel': '冰脊龍骨', 'limit': '界限', 'mixing': '混合', 'mound': '冰丘',
    'multiplication': '增殖', 'needle': '針', 'nuclei': '核', 'nucleus': '冰核', 'pellets': '冰粒', 'plain': '平原',
    'point': '點', 'pole': '極', 'prisms': '稜晶', 'raft': '冰筏', 'regime': '態', 'phase': '相', 'rise': '冰丘',
    'run': '冰流', 'saints': '冰聖徒期', 'shelf': '棚', 'structure': '結構', 'tongue': '舌', 'indicator': '指示器',
    'bulb': '球', 'haze': '霾', 'berg': '冰山', 'firn': '粒雪', 'fall': '瀑', 'low': '低壓', 'intensity': '強度',
    'ideal': '理想', 'independent': '獨立', 'indirect': '間接', 'indian': '印度', 'inclination': '傾角',
    'modification': '改變', 'inadvertent': '無意的', 'subrange': '子範圍', 'frequency': '頻率', 'coefficient': '係數',
    'rainfall': '降雨', 'initial': '初始', 'inland': '內陸', 'duration': '持續時間', 'variation': '變化', 'standard': '標準',
    'tides': '內潮汐', 'atmosphere': '大氣', 'synoptic': '天氣', 'dust': '塵', 'zone': '帶', 'potential': '位勢',
    'thickness': '厚度', 'period': '週期', 'gravity': '重力', 'coordinate': '座標', 'industrial': '工業',
    'induction': '感應', 'incoherent': '非相干', 'coherent': '相干', 'inference': '推論', 'rain': '雨', 'aridity': '乾燥',
    'continentality': '大陸性', 'wetness': '濕潤度', 'evaporating': '蒸發', 'horizontal': '水平', 'area': '面積',
    'circulation': '環流', 'fluid': '流體', 'radar': '雷達', 'atmospheric': '大氣', 'liquid': '液態', 'sunshine': '日照',
}

exact_translation.update({
    'index correction': '指數校正', 'index cycle': '指數循環', 'index error': '指數誤差',
    'index of aridity': '乾燥度指數', 'index of continentality': '大陸性指數',
    'index of evaporating surface of horizontal area': '水平蒸發面指數', 'index of wetness': '濕潤度指數',
    'infrasonic': '次聲的', 'infrasonic observatory': '次聲觀測站',
    'instrument weather': '儀器氣象條件', 'IFR weather': '儀器飛航天氣', 'IFR terminal minimums': '儀器進場最低標準',
    'isobaric chart': '等壓面圖', 'isotach chart': '等風速圖', 'isohyetal map': '等雨量圖',
    'isallobaric chart': '等變壓圖', 'isothermal': '等溫的', 'isobaric': '等壓的', 'isentropic': '等熵的',
    'isochoric': '等容的', 'isokinetic': '等速的', 'isosteric': '等容吸附的', 'isopycnic': '等密度的',
    'isodynamic': '等磁力的', 'isotropic': '各向同性的', 'isallobaric': '等變壓的',
    'ice cap': '冰冠', 'ice feathers': '冰羽', 'ice formation on aircraft': '航空器結冰', 'ice rind': '薄冰殼',
    'iceberg': '冰山', 'iced firn': '結冰粒雪', 'icefall': '冰瀑', 'Icelandic low': '冰島低壓', 'icicle': '冰柱',
    'icing level': '積冰高度', 'icing-rate meter': '積冰速率計', 'ideal gas': '理想氣體',
    'identical twin integrations': '同型雙重積分試驗', 'ice apron': '冰裙', 'ice band': '冰帶', 'ice bands': '冰帶',
    'ice bay': '冰灣', 'ice blink': '冰映光', 'ice breakup': '冰裂解', 'ice cover': '冰覆蓋', 'ice crust': '冰殼',
    'ice day': '冰日', 'ice desert': '冰荒漠', 'ice drift': '冰漂移', 'ice edge': '冰緣', 'ice field': '冰原區',
    'ice flow': '冰流', 'ice flowers': '冰花', 'ice foot': '岸冰緣', 'ice front': '冰緣面', 'ice island': '冰島體',
    'ice jam': '冰塞', 'ice keel': '冰脊龍骨', 'ice layer': '冰層', 'ice limit': '冰界限', 'ice mixing ratio': '冰相混合比', 'ice mound': '冰丘',
    'ice multiplication': '冰晶增殖', 'ice needle': '冰針', 'ice plain': '冰原平地', 'ice point': '冰點', 'ice pole': '冰極',
    'ice prisms': '冰稜晶', 'ice raft': '冰筏', 'ice regime phase': '冰況相位', 'ice rise': '冰丘隆起', 'ice run': '流冰',
    'Ice Saints': '冰聖徒期', 'ice shelf': '冰棚', 'ice storm': '冰暴', 'ice stream': '冰流帶', 'ice structure': '冰結構',
    'ice tongue': '冰舌', 'ice-accretion indicator': '積冰指示器', 'ice-bulb temperature': '冰球溫度',
    'ice-crystal cloud': '冰晶雲', 'ice-crystal haze': '冰晶霾',
})


def polish(text: str) -> str:
    text = re.sub(r'\s+', ' ', text).strip()
    text = text.replace(' ,', '，').replace(' .', '。')
    if not text.endswith('。'):
        text += '。'
    text = text.replace(' 0°C', '0°C').replace(' 90 至 150', '90 至 150')
    return text


def generic_translation(term: str) -> str:
    if term in exact_translation:
        return exact_translation[term]
    t = term
    for en in sorted(phrase_map, key=len, reverse=True):
        t = re.sub(rf'(?i)\b{re.escape(en)}\b', phrase_map[en], t)
    t = re.sub(r'\b(of|the|and|on)\b', '', t, flags=re.I)
    t = t.replace('–', '—')
    t = t.replace('-', '—') if re.search(r'[A-Za-z]+-[A-Za-z]+', term) and term.lower() not in ['jet-effect wind','ice-accretion indicator','ice-bulb temperature','ice-crystal cloud','ice-crystal haze'] else t
    t = re.sub(r'\s+', ' ', t).strip(' -—')
    if re.fullmatch(r'[A-Z][A-Z0-9\-]*', term):
        return term
    return t


def generic_definition(term: str, zh: str) -> str:
    low = term.lower()
    patterns = [
        (['wind'], lambda: f'指與「{zh}」相關的風系、局地風或風場型態，著重其形成機制、風向風速分布及天氣影響。'),
        (['front'], lambda: f'指與「{zh}」相關的鋒面、鋒區或其空間邊界結構，常用於描述不同氣團之間的過渡帶。'),
        (['wave'], lambda: f'指與「{zh}」相關的波動現象，著重其恢復力來源、傳播特徵與能量交換。'),
        (['current'], lambda: f'指與「{zh}」相關的水流、洋流或電流系統，重點在其流向、強度、成因與輸送作用。'),
        (['stream'], lambda: f'指與「{zh}」相關的氣流、冰流或水流帶狀結構，著重其主軸、速度分布及動力特徵。'),
        (['layer'], lambda: f'指與「{zh}」相關的層狀結構，常用於描述大氣、海洋或地表附近具有相對一致性質的區域。'),
        (['surface'], lambda: f'表示某一物理量相同或具特定動力、熱力條件所構成的曲面。'),
        (['chart','map'], lambda: f'用於呈現「{zh}」空間分布、等值結構或分析結果的圖件。'),
        (['line'], lambda: f'以線狀方式表示某一物理量相同、變化集中或特徵帶狀分布的分析要素。'),
        (['index'], lambda: f'用以量化「{zh}」相關狀態、強度、頻率或特性的指標。'),
        (['ratio'], lambda: f'表示「{zh}」所對應成分相對於基準量之比例或混合關係。'),
        (['temperature'], lambda: f'指與「{zh}」相關的溫度量、特徵溫標或熱力診斷參數。'),
        (['radar'], lambda: f'用於偵測目標位置、回波或電離層／大氣結構的雷達系統或觀測方法。'),
        (['satellite','system'], lambda: f'指與「{zh}」相關的衛星、作業系統或整合觀測架構，用於資料蒐集、傳輸或環境監測。'),
        (['image'], lambda: f'指以感測器觀測結果形成之「{zh}」圖像或其處理產品，用於判識空間結構與場分布。'),
        (['spectrum'], lambda: f'描述能量、頻率或波動分布特性的譜形或譜函數。'),
        (['recorder'], lambda: f'用於連續記錄「{zh}」相關觀測量隨時間變化的儀器。'),
        (['probe','meter','counter'], lambda: f'用於量測、偵測或計數「{zh}」相關物理量的儀器。'),
        (['spectrometer'], lambda: f'用於解析「{zh}」波段光譜分布與物質特性的儀器。'),
        (['radiation'], lambda: f'指與「{zh}」相關的電磁輻射或其能量傳輸過程。'),
        (['circulation'], lambda: f'指與「{zh}」相關的環流型態，著重質量輸送、熱量交換與動力平衡。'),
        (['instability'], lambda: f'描述流體或大氣系統對微小擾動易於增幅的性質，是對流與動力發展的重要條件。'),
        (['inversion'], lambda: f'指與「{zh}」相關的逆轉或逆溫結構，常用於描述垂直分布與穩定度異常。'),
        (['ion'], lambda: f'指與「{zh}」相關的離子、游離作用或電離層物理現象。'),
        (['ice'], lambda: f'指與「{zh}」相關的冰相過程、冰體結構或結冰現象，常見於雲微物理、冰凍圈與航空氣象。'),
        (['law','rule'], lambda: f'表示用於描述「{zh}」關係的定律、規則或經驗準則。'),
        (['analysis','method','model'], lambda: f'用於描述、求解或分析「{zh}」相關過程的理論、方法或模式。'),
    ]
    for keys, fn in patterns:
        if all(k in low for k in keys):
            return fn()
    if re.fullmatch(r'[A-Z][A-Z0-9\-]*', term):
        return f'「{term}」為相關領域常用縮寫，通常指特定觀測系統、分析產品、組織或技術名詞，確切內涵需依使用情境判定。'
    if low.endswith('water'):
        return f'指與「{zh}」相關的水團或水體類型，著重其形成區域、溫鹽結構與輸送特性。'
    if low.endswith('fluid'):
        return f'為流體力學中的理想化或特定性質流體概念，用於描述其動力與熱力行為。'
    if low.endswith('gas'):
        return f'指具有特定熱力假設或組成特徵的氣體概念，用於大氣與流體理論分析。'
    return f'「{zh}」為氣象、海洋、水文、氣候、遙測或相關地球科學中的專業術語，其確切意義需依使用情境、觀測對象與理論脈絡判定。'


def refine_translation(term: str, zh: str) -> str:
    replacements = [
        ('  ', ' '), ('圖 圖', '圖'), ('風 風', '風'), ('流 流', '流'), ('層 層', '層'),
        ('等壓 的', '等壓的'), ('等熵 的', '等熵的'), ('等溫 的', '等溫的'), ('各向同性 的', '各向同性的'),
        ('儀器 飛航 規則', '儀器飛航規則'), ('紅外 影像', '紅外影像'), ('紅外 輻射', '紅外輻射'),
        ('紅外 光譜儀', '紅外光譜儀'), ('內部 邊界層', '內部邊界層'), ('熱帶輻合 帶', '熱帶輻合帶'),
        ('等風速 圖', '等風速圖'), ('等雨量 圖', '等雨量圖'), ('等壓 面圖', '等壓面圖'),
    ]
    for a,b in replacements:
        zh = zh.replace(a,b)
    zh = re.sub(r'([\u4e00-\u9fff])\s+([\u4e00-\u9fff])', r'\1\2', zh)
    return zh.strip()


for letter, src in source_files.items():
    terms = [line.strip() for line in src.read_text().splitlines() if line.strip()]
    data = []
    for term in terms:
        zh = refine_translation(term, generic_translation(term))
        definition = exact_definition.get(term) or generic_definition(term, zh)
        definition = polish(definition)
        data.append({
            'english': term,
            'traditional_chinese': zh,
            'definition_cht': definition,
        })
    out = DATA / f'{letter}_terms_all_cht.json'
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
    print(letter.upper(), len(data), out)
    print('first:', data[0]['english'])
    print('last :', data[-1]['english'])
